### ISSUE TITLE
Performance issues with the dotnet sdk upload-method

### ISSUE THREAD

**Issue by Ivica78** [dracoon/dracoon-csharp-sdk#10]
running into issues with the .NET Dracoon Sdk, 

Whenever trying to upload a file via the UploadFile-method from the INodes-interface, observation is made with a very slow upload-speed, which is significantly slower than the upload-speed when uploading directly over the web-app. This seems to result in semi-frequent timeouts (see error messages in the attachments) when uploading larger files (2GB+) and sometimes the upload just stops without any error message. 
 .NET 8.0 is used and the newest version of the Dracoon Sdk (5.1.0), though this problem also occurred with older versions of both.
Please check 

![image](https://github.com/user-attachments/assets/555ede57-824b-4912-8e3b-cc537c05f49b)

**Comment by unbekanntes-pferd** [comment]
A suggestion based on previous feedback to the sync method `UploadFile`: please use the async method `StartUploadFileAsync` to avoid running into such issues if possible.

**Comment by wdDiamant** [comment]
Thanks for the suggestion! We've implemented the StartUploadFileAsync method, but we can't say anything definitive about the timeouts just yet. However, the speed is still a lot slower compared to using the web app, and seemingly the same, or even slower, as with the UploadFile method.

**Comment by unbekanntes-pferd** [comment]
Could you please clarify a bit more how you compare upload speed? Are you comparing single file uploads or multiple files? Our web app uses a chunk size of 32 MB - if you upload larger files and use a low chunk size (I believe the default is the minimum of 5 MB) this will create overhead (requiring multiple requests). Could you therefore try with a larger chunk size?
You should be able to set the chunk size via https://github.com/dracoon/dracoon-csharp-sdk/blob/baeb81e396e6e4cfc3633386992d4d2c8dcac78d/DracoonSdk/SdkPublic/DracoonHttpConfig.cs#L69 
for the client.

**Comment by wdDiamant** [comment]
Thank you for the help, we actually missed this config variable. After increasing the chunk size, we now observe a faster upload speed for single file uploads. However, what are the potential disadvantages of using a higher chunk size?

**Comment by unbekanntes-pferd** [comment]
Basically, this affects how much you might need to re-upload in case you 
- use retry (see https://github.com/dracoon/dracoon-csharp-sdk/blob/baeb81e396e6e4cfc3633386992d4d2c8dcac78d/DracoonSdk/SdkPublic/DracoonHttpConfig.cs#L40) 
- connection fails for a request
If you use a very large chunk size and there's a connection timeout and you need to retry, you will need to re-upload more (or less) bytes depending on the chunk size.

Overall, you'll need to find a middle ground between http overhead and retry effort.

**Comment by wdDiamant** [comment]
Thank you very much for the help. You can close the issue!
